spring:
   datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/quartz?useSSL=false
      username: root
      password:
   quartz:
      job-store-type: jdbc
      jdbc:
         initialize-schema: ALWAYS 
      properties:
         org:
            quartz:
               threadPool:
                  threadCount: 5
   mail: smtp.gmail.com
   port: 587
   username: 
   password:
   properties:
      mail:
         smtp:
            auth: true
            starttls:
               enable: true